web-infra-dev/garfish

packages/runtime/browser-vm/src/modules/document.ts
packages/runtime/browser-vm/src/proxyInterceptor/document.ts

Some javascript libraries may use “key in document“ in if expression，up to now，these always return false。For example, https://github.com/sindresorhus/screenfull.js/blob/main/dist/screenfull.js

feat: add the has proxy for document

---

package.json
packages/browser-snapshot/package.json
packages/browser-vm/package.json
packages/core/package.json
packages/garfish/package.json
packages/hooks/package.json
packages/loader/package.json
packages/remote-module/package.json
packages/router/package.json
packages/utils/package.json
packages/utils/src/utils.ts

Reverts modern-js-dev/garfish#236

Revert "fix(utils): Conversion relative path to the absolute path to failure is not blocked"

---

packages/browser-vm/__tests__/dom.spec.ts
packages/browser-vm/src/dynamicNode/index.ts
packages/browser-vm/src/dynamicNode/processor.ts
packages/browser-vm/src/pluginify.ts
packages/browser-vm/src/sandbox.ts
packages/browser-vm/src/utils.ts

[style-components](https://styled-components.com/docs/api#stylesheetmanager)在生产环境下，默认样式是通过[insertRule](https://developer.mozilla.org/zh-CN/docs/Web/API/CSSStyleSheet/insertRule) api插入样式规则的（而不是传统的样式文本），这种style标签有个问题，在dom节点被卸载后，sheet数据就丢失了的，所以需要记录和还原。

feat: support style component

---

package.json
packages/bridge/package.json
packages/browser-snapshot/package.json
packages/browser-vm/package.json
packages/browser-vm/src/pluginify.ts
packages/browser-vm/src/proxyInterceptor/document.ts
packages/browser-vm/src/proxyInterceptor/global.ts
packages/browser-vm/src/proxyInterceptor/shared.ts
packages/browser-vm/src/sandbox.ts
packages/core/package.json
packages/garfish/package.json
packages/hooks/package.json
packages/loader/package.json
packages/remote-module/package.json
packages/router/package.json
packages/utils/package.json
packages/utils/src/utils.ts
packages/web-component/package.json

* function.prototype.toString may be isn't function in a lower version browser
* onselectstart、ondragstart can't set to proxy document
* vmsandbox：can't clear side effect sync，child app unmout maybe in macro task
* safari 13.x（Proxy object's 'set' trap returned falsy value for property）
* Reflect.set will be called in the set callback, and the DefineProperty callback will be triggered after Reflect.set is called.
* but the descriptor values ​​writable, enumerable, and configurable on safari 13.x version are set to false for the second time
* Set the default when calling defineProperty through set ​​writable, enumerable, and configurable default to true
* safari 13.x default use strict mode，descriptor's ​​writable is false can't set again

Fix/is function.prototype.toString isn't function and onselectstart、ondragstart can't set to proxy document

---

packages/browser-vm/src/dynamicNode/processor.ts
packages/core/src/module/resource.ts
packages/loader/src/index.ts

类似`<script crossorigin="use-credentials" src="xxx.js"></script>`这种带有`use-credentials`跨域标记的，请求时应该要允许携带cookie。

feat: support cross origin script with 'use-credentials' flag

---

jest.config.js
packages/core/__tests__/loadApp.spec.ts
packages/core/__tests__/vue3App.html
packages/core/src/config.ts
packages/core/src/garfish.ts

assert app entry after beforeLoad hook
assertion app entry  After the beforeLoad hook is called
application may be re-registered during beforeLoad, resulting in inaccurate information. so It is necessary to put off the assertion judgment of app entry  after beforeLoad is called to  ensure that the final application information is obtained. And after that we can make the assertion judgment of the app entry.
For example, for the scenario of using the get-app-list plugin, we need that feature.

feat(core): assertion app entry After the beforeLoad hook is called

---

packages/browser-vm/src/modules/uiEvent.ts

fix(vm-sandbox): Babel cannot correctly identify the MouseEvent  in the code as a native class
#450 
* fixed #450
* no tests need to be added

fix(vm-sandbox): Babel cannot correctly identify the MouseEvent  in the code as a native class

---

packages/loader/__tests__/styleProcess.spec.ts
packages/loader/src/managers/style.ts

1. 将无url()的@import语句转换为有url()，以供后续统一处理；
2. @charset在&lt;style&gt;无意义，直接移除；
3. url()可匹配带文件名带括号的资源
<https://github.com/modern-js-dev/garfish/issues/446>
1. 支持了无url()的@import语句，兼容性更好
2. 顺带移除了可能出现的@charset语句，减少控制台warning
3. 优化了url()匹配模式，能兼容更多合理的资源名
repo中无相关test case，可手动在 <https://github.com/yanni4night/garfish-issue-reproduction/tree/issue-446> 验证。

fix(loader): support @charset removing and @import without url()

---

packages/browser-snapshot/src/index.ts

fix issue#459: GarfishBrowserSnapshot plugin use global variables, causing sub app configurations to pollute each other #459
GarfishBrowserSnapshot plugin use global variables, causing sub app configurations to pollute each other.
A variable is used in the GarfishBrowserSnapshot plugin to identify whether an application has enabled snapshot sandbox mode, but unfortunately, it is a global variable, which causes the sub-application to be loaded later to be polluted by the previous sub-application，affecting the initial state of the plugin.
For example, if the previous app closes the snapshot sandbox, the apps loaded later will also be judged to close the sandbox because the global variable has been marked as false, which will result in an application initialization error, as a result, the …

fix(snapshot-sandbox): GarfishBrowserSnapshot plugin use global variables, causing sub app configurations to pollute each other fix issue #459

---

packages/core/__tests__/appInstance.spec.ts
packages/core/__tests__/loadApp.spec.ts
packages/core/src/module/app.ts

feat(core): can get activeApps before rendering
* some plugin need get the current app instance before rendering function call

feat(core): add app to activeApps in rendering

---

packages/browser-vm/__tests__/dom-side-effect.spec.ts
packages/browser-vm/src/dynamicNode/processor.ts

* deferClearEffects memory leak
#462 
* After the vm sandbox is turned on, the vm sandbox will collect the dom nodes added to the document by the sub-application during rendering and running, to ensure that the nodes are also destroyed when the sub-application is uninstalled
* In order to avoid collecting nodes in the sub-application rendering container (nodes in the rendering container will be destroyed following the destruction of the root node)
* However, vue and react framework components will add nodes as a whole instead of part of them when rendering to improve performance, so that when nodes are not really added to the document flow, the !this.rootElement.contains(parentNode) judgment is always false
[] need add

fix(vm-sandbox): deferClearEffects memory leak

---

.eslintrc.js
.github/pull_request_template.md
dev/app-vue-2/src/shims-vue.d.ts
dev/app-vue-2/src/shimsVue.d.ts
dev/app-vue-3/src/shims-vue.d.ts
dev/app-vue-3/src/shimsVue.d.ts
dev/app-vue-vite/src/shimsVue.d.ts
package.json
packages/core/src/module/app.ts

refactor(core): Add an app instance to activeApps before rendering
* can get activeApps when app start mount
* don't need add test

refactor(core): Add an app instance to activeApps before rendering

---

packages/core/__tests__/loadApp.spec.ts
packages/core/src/config.ts

fix bug :  when loadApp before the app been registered successfully, or appName does not exists, the appInfo in `beforeLoad` hook call  will be  undefined.
yes.

fix(core): loadApp add default appInfo

---

packages/core/__tests__/esmLoader.spec.ts
packages/core/__tests__/resources/js/circularEsmA.js
packages/core/__tests__/resources/js/circularEsmB.js
packages/core/__tests__/resources/js/esmA.js
packages/core/__tests__/resources/js/esmB.js
packages/core/__tests__/resources/js/esmC.js
packages/core/package.json
packages/core/src/module/esModule.ts
packages/loader/src/appCache.ts
packages/loader/src/index.ts
pnpm-lock.yaml

利用社区的`es-module-lexer`方案重写了`ESModuleLoader`的import解析逻辑，现在的正则匹配方式没有很好地处理一些边界case，比如console.error(\`import Vue from 'vue';\`)，我们的项目里确实出现了一个库，里面有个console的提示就是类似这么写的。

fix: enhance esm parser

---

packages/bridge-react-v18/src/types.d.ts
packages/bridge-react/src/types.d.ts
packages/bridge-vue-v2/src/types.d.ts
packages/bridge-vue-v3/src/types.d.ts

There has type error where had import `@garfish/bridge-*`, such as where `dev/app-react-18/src/root.tsx:L6`
Bridge had define Props Info for an app info, but it will be meaningful which renamed be AppInfo than it, so I did to redefine to AppInfo
Reinstall and reopen `dev/app-react-18/src/root.tsx:L6`

Feat: Redefine AppInfo by PropsInfo

---

README.ch.md

* Found the url of quick start is wrong in readme of Chinese version.
[#533](https://github.com/modern-js-dev/garfish/issues/533)
* Fix url
Add tests to ensure that user can be redirected to correct address

fix: quick start link in cn readme

---

package.json
packages/bridge-react-v18/package.json
packages/bridge-react/package.json
packages/bridge-vue-v2/package.json
packages/bridge-vue-v3/package.json
packages/browser-snapshot/package.json
packages/browser-vm/package.json
packages/browser-vm/src/sandbox.ts
packages/core/package.json
packages/core/src/module/app.ts
packages/css-scope/package.json
packages/es-module/package.json
packages/garfish/package.json
packages/hooks/package.json
packages/loader/package.json
packages/remote-module/package.json
packages/router/package.json
packages/test-suite/package.json
packages/utils/package.json
packages/utils/src/utils.ts

fix(sandbox): use micro task replace macro task and delete restore document.currentScript behavior
* document.currentScript default behavior is to clear after microtask
* https://html.spec.whatwg.org/#execute-the-script-block
* https://bugzilla.mozilla.org/show_bug.cgi?id=1620505
* use delete to restore document.currentScript default  behavior

fix(sandbox): use micro task replace macro task and delete restore document.currentScript behavior

---

packages/browser-vm/src/modules/network.ts

fakeFetch函数中并没有对 input 的类型做判断 导致fetch请求失败。addSourceList方法中url参数需要是string类型

fix(browser-vm): fakeFetch method input type judgment

---

packages/core/src/module/app.ts

BaseUrl should be provided, or the collect condition will filter the source url, which will cause monitor sdk lose report

fix: add baseUrl for sourceList to avoid lose collection

---

packages/core/__tests__/loadApp.spec.ts
packages/loader/src/index.ts

fix(loader): fix the loader return the same loader when multi apps mount at the same time
When multiple applications with the same entry are mounted at the same time, garfish will collect the dom created by the previous application as a side effect into the side effect category of the last sub-application. When the last sub application is unmount, it will cause all applications to be uninstalled.
This is because the loader of garfish will cache the loader instance for the same entry url, and return the previous loader instance when the entry is the same. In this way, when multiple sub applications are mounted at the same time, if these applications have the same entry, they will point to the same loader instance. In the vm sandbox, the document object of the loader will be rewritten to …

fix(loader): fix the loader return the same entryManager when multi apps mount at the same time

---

packages/utils/__tests__/domApis.spec.ts
packages/utils/__tests__/templateParse.spec.ts
packages/utils/src/domApis.ts
packages/utils/src/templateParse.ts

fix bugs:
* SVG camel tag is not support: add SVG judge for template parse
* SVG setAttribute xmlns:xlink failed: make sure the prefix is `xlink`, only `xlink:XXX` attribute need xlink namespace.
* SVG camel tag is not support https://github.com/modern-js-dev/garfish/issues/585
* SVG setAttribute xmlns:xlink failed https://github.com/modern-js-dev/garfish/issues/584
garfish render SVG in template error.
* SVG camel tag is not support: test SVG `feFlood` tag and `DIV`, make sure toLowercase is enable for normal tag.
* SVG setAttribute xmlns:xlink: test `xmlns:xlink` and `xlink:href`, make sure only `xlink:href` is set with xlink namespace.

fix: issue SVG camel tag is not support #585, SVG setAttribute xmlns:xlink failed #584

---

website/docs/blog/sourcemap.md

缺少空格，markdown 识别出来的链接会带上最后的 `)` ，导致跳转错误。

docs: 修复 markdown 链接识别错误

---

packages/core/__tests__/loadApp.spec.ts
packages/core/src/garfish.ts

fix: lost appInfo information after the second merge in loadApp

fix(core): fix loadApp lost appInfo information after the second merge

---

packages/core/src/plugins/preload.ts

preload这个api用户可以在任何时间调用。
但是目前没有判断这个这个是否被preload插件自动获取了，或者用户调用了preload后，也没有写入loadedMap。
所以我觉得这块可以加这方面的逻辑。
减少多余的函数执行。
- [] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
- [] I have added tests to cover my changes.

fix(preload): preload api shouldn't invoke if loaded

---

packages/browser-vm/__tests__/__snapshots__/dynamic-style.spec.ts.snap
packages/browser-vm/__tests__/dom-side-effect.spec.ts
packages/browser-vm/__tests__/dom.spec.ts
packages/browser-vm/__tests__/dynamic-style.spec.ts
packages/browser-vm/src/dynamicNode/index.ts
packages/browser-vm/src/dynamicNode/processor.ts
packages/browser-vm/src/pluginify.ts
packages/browser-vm/src/sandbox.ts
packages/browser-vm/src/types.ts
packages/browser-vm/src/utils.ts

Fixed:
- Some style rules inserted by `insertRule()` are not transformed by the `StyleManager` 
(fixed by ~~overwriting `insertRule()` on the first time getting `style.sheet`~~ fake `sheet`)
- `cssRules` is empty after the app remount in case of the app was detached before "unmount"
(fixed by changing the timing of saving cssRules)
- styled-components cannot `insertRule()` after the app remount because they keep the first `sheet` instance.
(fixed by returning a fake `sheet` that always passthrough operations to the latest real `sheet`)

fix: styled-components / insertRule

---

packages/es-module/__tests__/case/exportAll/m1.js
packages/es-module/__tests__/case/exportAll/m2.js
packages/es-module/__tests__/case/exportAll/m3.js
packages/es-module/__tests__/index.spec.ts
packages/es-module/src/compiler/index.ts
packages/es-module/src/runtime.ts

fix(es-module): fix bug when export * from 'xx'

---

packages/loader/src/index.ts
packages/loader/src/utils.ts

fix(loader): fix the requestConfig type definition in beforeLoad

fix(loader): fix the requestConfig type definition in beforeLoad

---

packages/browser-vm/src/dynamicNode/index.ts
packages/browser-vm/src/pluginify.ts
packages/browser-vm/src/proxyInterceptor/document.ts
packages/browser-vm/src/types.ts
packages/core/src/config.ts
packages/core/src/interface.ts
pnpm-lock.yaml
website/src/components/config/_sandbox.mdx

* Avoid escaping the sandbox when an element created through the create Element ns api gets the owner document
* Added the owner document configuration

fix: Avoid elements created through the create element ns api from escaping the sandbox

---

packages/core/src/module/app.ts
packages/core/src/module/resource.ts
packages/loader/src/managers/template.ts

修复的问题参考[此issue](https://github.com/web-infra-dev/garfish/issues/659)
改动点：
- 将findAttributeValue中的`||`修改为`??`
- 对逻辑受影响的地方进行调整（包含两处：packages/core/src/module/resource.ts中的crossorigin，以及packages/core/src/module/app.ts中的no-entry。其他使用findAttributeValue的地方目测不受影响）
[https://github.com/web-infra-dev/garfish/issues/659](https://github.com/web-infra-dev/garfish/issues/659)

fix: TemplateManager.findAttributeValue对值为空的HTML布尔属性处理错误

---

dev/app-main/src/constant.ts
dev/app-react-16/public/exclude-dynamic.js
dev/app-react-16/public/exclude.js
dev/app-react-16/public/index.html
packages/browser-vm/src/dynamicNode/processor.ts
packages/browser-vm/src/pluginify.ts
packages/browser-vm/src/types.ts
packages/core/src/interface.ts
packages/core/src/module/app.ts
packages/core/src/module/resource.ts
pnpm-lock.yaml
website/docs/issues/childApp.md
website/src/components/config/_sandbox.mdx

* feat(sandbox): support for filtering scripts
```diff
Garfish.run({
apps: [
{
name: 'react16',
activeWhen: '/react16',
entry: getProxyHost('dev/react16'),
sandbox: {
+        excludeAssetFilter: (url: string) => {
+         return url.includes('exclude');
+       },
},
},
]
})
```

feat(sandbox): support for filtering scripts

---

cypress/e2e/1-the-whole-process/visit-sub-app.spec.js
dev/app-main/src/constant.ts
dev/app-react-17/public/a.css
dev/app-react-17/public/b.css
dev/app-react-17/public/index.html
packages/browser-vm/__tests__/dynamic-link.spec.ts
packages/browser-vm/src/dynamicNode/processor.ts
packages/browser-vm/src/pluginify.ts
packages/browser-vm/src/sandbox.ts
packages/browser-vm/src/types.ts
packages/core/src/config.ts
packages/core/src/interface.ts
packages/core/src/module/app.ts
packages/core/src/module/resource.ts
pnpm-lock.yaml
website/src/components/config/_sandbox.mdx

* feat(sandbox): add disableLinkTransformToStyle sandbox config

feat(sandbox): add disableLinkTransformToStyle sandbox config

---

packages/bridge-react/src/reactBridge.ts

Fix errorBoundary feature for reactBridge

fix(bridge): fix errorBoundary feature for reactBridge

---

website-new/docs/guide/quick-start/index.md

The link jump is abnormal.
Clicking on the link of micro front-end architecture design jumps to the 404 page.

docs: update architecture blog url

---

packages/browser-vm/src/modules/network.ts

Fix compatibility issue with fakefetch when using Axios fetch adapter.
修复browser-vm模块fakefetch中判断不存在signal时自动添加逻辑与axios的fetch adapter冲突的问题。
axios中fetch adapter会向fetch传入Request实例，导致fakefetch 判断signal是否存在的逻辑失效。

fix(browser-vm): vm network fakefetch to be compatible with the axios fetch adapter

---

packages/browser-vm/__tests__/sandbox.spec.ts
packages/browser-vm/src/proxyInterceptor/shared.ts

```ts
(window as any).a = function () {
return 11;
};
(window as any).a.aa = 1;
const vm = new VM({
namespace: '111',
});
vm.start();
// get 11
vm.execScript(`console.log(window.a());`);
// get undefined, but expect `1`
vm.execScript(`console.log(window.a.aa);`);
```

fix: fix the error of passing parameters when binding function to window
