web-infra-dev/garfish

- .github/workflows/documentation.yml
> chore: modify workflows script

- .github/workflows/documentation.yml
> chore: add docs workflows

- .github/workflows/documentation.yml
> chore: Adjust the workflows jobs

- .github/workflows/documentation.yml
> fix-workflow-syntax

- website/CNAME
> chore: add CNAME

- website/CNAME
> chore: modify  CNAME

- packages/runtime/core/src/garfish.ts
-  loadApp should use this.options.props as `fallback props`
> fix: props should pass to subapplication

- website/docs/napi/index.md
> fix: docs content

- packages/runtime/browser-snapshot/index.js
- packages/runtime/browser-vm/index.js
- packages/runtime/core/index.js
- packages/runtime/garfish/index.js
- packages/runtime/loader/index.js
- packages/runtime/remote-module/index.js
- packages/runtime/router/index.js
- packages/runtime/utils/index.js
> fix: add missing index js

- dev/main/index.ts
- packages/runtime/browser-vm/src/utils.ts
- packages/runtime/loader/package.json
- packages/runtime/loader/src/managers/htmlParse.ts
- packages/runtime/loader/src/managers/template.ts
html parse optimization, double the speed
> refactor: modify html-parse

- website/i18n/en/docusaurus-plugin-content-docs/current/community/discuss.md
- website/i18n/en/docusaurus-plugin-content-docs/current/guide/advance/__meta__.md
- website/i18n/en/docusaurus-plugin-content-docs/current/guide/advance/loadApp.md
- website/i18n/en/docusaurus-plugin-content-docs/current/guide/develop/__meta__.md
- website/i18n/en/docusaurus-plugin-content-docs/current/guide/develop/fromZero.md
- website/i18n/en/docusaurus-plugin-content-docs/current/guide/start/__meta__.md
- website/i18n/en/docusaurus-plugin-content-docs/current/guide/start/index.md
- website/i18n/en/docusaurus-plugin-content-docs/current/issues/childApp.md
- website/i18n/en/docusaurus-plugin-content-docs/current/issues/multipleApp.md
- website/i18n/en/docusaurus-plugin-content-docs/current/issues/oldApp.md
- website/i18n/en/docusaurus-plugin-content-docs/current/issues/router.md
- website/i18n/en/docusaurus-plugin-content-docs/current/issues/style.md
- website/i18n/en/docusaurus-plugin-content-docs/current/napi/attributes/loadApp.md
- website/i18n/en/docusaurus-plugin-content-docs/current/napi/attributes/props.md
- website/i18n/en/docusaurus-plugin-content-docs/current/napi/attributes/router.md
- website/i18n/en/docusaurus-plugin-content-docs/current/napi/index.md
- website/i18n/en/docusaurus-plugin-content-docs/current/napi/instance.md
> chore: fix build docs

- dev/subApp/src/main.js
- packages/runtime/browser-vm/src/dynamicNode/index.ts
- packages/runtime/browser-vm/src/dynamicNode/processor.ts
* use default dom to insert
* use default dom to delete
> fix: strict insert style

- .github/workflows/documentation.yml
- lerna.json
- package.json
- website/docusaurus.config.js
- website/package.json
> fix: fix build docs

- .github/workflows/documentation.yml
> fix: fix build script

- packages/runtime/browser-snapshot/src/index.ts
- packages/runtime/browser-vm/__tests__/methods.spec.ts
- packages/runtime/browser-vm/src/sandbox.ts
- packages/runtime/browser-vm/src/types.ts
- packages/runtime/core/src/config.ts
- packages/runtime/core/src/interface/index.ts
- packages/runtime/garfish/src/index.ts
- yarn.lock
> chore: modify with options

- dev/vue/src/components/microApp.vue
- packages/runtime/router/src/linkTo.ts
> fix: router push not trigger app refresh

- cypress/integration/2-the-sandbox/set-global-variable.spec.js
- dev/react/src/App.js
- dev/react/src/components/sandbox/setProxyVariable.js
- packages/runtime/browser-vm/src/modules/history.ts
- packages/runtime/browser-vm/src/proxyInterceptor/document.ts
- packages/runtime/browser-vm/src/proxyInterceptor/shared.ts
* fix history scrollRestoration set
> fix: can't set history scrollRestoration

- packages/core/src/garfish.ts
> fix(core): Fix the first time executing run function would throw warning

- .github/workflows/release-changelog.yml
Reverts modern-js-dev/garfish#216
> Revert "chore(workflow): ignore lapha and beta changelog tags"

- package.json
- packages/browser-snapshot/package.json
- packages/browser-vm/package.json
- packages/core/package.json
- packages/garfish/package.json
- packages/hooks/package.json
- packages/loader/package.json
- packages/remote-module/package.json
- packages/router/package.json
- packages/utils/package.json
- packages/utils/src/utils.ts
> fix(utils): Conversion relative path to the absolute path to failure is not blocked

- packages/core/src/garfish.ts
* Before registration application may not be state run as otherwise it will trigger the application routing
> fix: Repair beforeEach initialization trigger many times

- package.json
- packages/browser-snapshot/package.json
- packages/browser-vm/__tests__/dynamic.spec.ts
- packages/browser-vm/package.json
- packages/browser-vm/src/dynamicNode/processor.ts
- packages/browser-vm/src/pluginify.ts
- packages/browser-vm/src/sandbox.ts
- packages/core/package.json
- packages/garfish/package.json
- packages/hooks/package.json
- packages/loader/package.json
- packages/remote-module/package.json
- packages/router/package.json
- packages/utils/package.json
- pnpm-lock.yaml
* Application of continuous dynamic add script tags, code execution content and onload event trigger abnormal sequence
*  If the application 1 add script first, add script second application 2, correct execution
* before：1 script content、2 script content 、1 onload、2 onload
* after：1 script content、1 onload、2 script content、2 onload
> fix: Application of onload event and micro macro quest

- packages/loader/src/managers/template.ts
> fix(loader): source list duplicate

- packages/core/src/module/app.ts
* mockbody highest priority
* svg tag include body tag
> fix(core): rootElement mockbody priority

- website/docs/guide/quick-start.md
> doc:fix typos

- packages/core/src/interface.ts
fix app mount and unmount interface
> chore: fix app mount and unmount interface

- scripts/release.js
> chore(workflow): fix tag push

- packages/core/src/plugins/performance/index.ts
- packages/core/src/plugins/performance/subAppObserver.ts
> fix: performance plugin statistics node in beforeLoad hook

- .github/workflows/changelog.yml
> chore(workflow): fix changelog workflow

- packages/router/src/index.ts
> fix(router): app is null can't get appInfo

- packages/core/src/module/app.ts
- packages/core/src/module/esModule.ts
- packages/loader/src/appCache.ts
- packages/loader/src/index.ts
- packages/loader/src/utils.ts
> fix: fix performance issue with computing resource size

- packages/core/src/plugins/fixHMR.ts
> fix(plugins:fixHMR): fix plugins fixHMR

- package.json
- packages/bridge/package.json
- packages/browser-snapshot/package.json
- packages/browser-vm/package.json
- packages/core/package.json
- packages/garfish/package.json
- packages/hooks/package.json
- packages/loader/package.json
- packages/remote-module/package.json
- packages/router/package.json
- packages/utils/package.json
> chore: fix version

- dev/main/src/config.ts
- package.json
- packages/browser-vm/__tests__/fetch.spec.ts
- packages/browser-vm/src/modules/network.ts
- packages/browser-vm/src/pluginify.ts
- packages/browser-vm/src/sandbox.ts
- packages/browser-vm/src/types.ts
- packages/core/src/interface.ts
- pnpm-lock.yaml
> chore: add fix base url feature

- packages/loader/src/managers/module.ts
- packages/remote-module/src/apis/preload.ts
- packages/remote-module/src/common.ts
> fix(remote-module): fix the bug of caching when there are redirects

- dev/app-main/src/components/App/index.tsx
- dev/app-main/src/components/root/index.tsx
- dev/app-main/src/config.ts
- dev/app-main/src/constant.ts
- dev/app-main/src/garfishInit.ts
- dev/app-main/src/index.tsx
- dev/app-react-17/src/components/App/index.tsx
- dev/app-react-17/src/index.tsx
> fix(examples): close sandbox when vite application

- dev/app-angular/custom-webpack.config.js
- dev/app-angular/src/app/pageNotFound/pageNotFound.component.html
- dev/app-main/src/components/constant.tsx
- dev/app-react-17/src/components/root/index.tsx
> fix(examples): fix angular router

- dev/app-main/src/components/mdStr.ts
> fix(examples): delete sensitive information in examples

- packages/core/src/module/app.ts
- packages/garfish/__tests__/run.spec.ts
> fix(core): async script can't emit eval hooks

- packages/browser-vm/src/dynamicNode/index.ts
Fix the problem that styles are inserted twice.
none.
none.
> fix(browser-vm): fix the problem that styles are inserted twice

- package.json
- pnpm-lock.yaml
> chore(workflow): fix release script

- website/docs/issues/childApp.md
- website/i18n/en/docusaurus-plugin-content-docs/current/issues/router.md
change garfish.bytedance.net to garfish.bytedance.com
> fix(website): change garfish.bytedance.net to garfish.bytedance.com

- .github/workflows/ci.yml
> chore: add codecov action

- .github/workflows/ci.yml
- package.json
- packages/core/__tests__/__snapshots__/preloadPlugin.spec.ts.snap
- packages/core/__tests__/loadApp.spec.ts
- packages/core/__tests__/preloadPlugin.spec.ts
- packages/core/src/plugins/preload.ts
fix(plugin-preload): The loading weight is set without preloading, and no fault tolerance is performed when the localStorage storage is full
* The loading weight is set without preloading
* and no fault tolerance is performed when the localStorage storage is full
> fix(plugin-preload): The loading weight is set without preloading, and no fault tolerance is performed when the localStorage storage is full

- website/docs/guide/API/registerApp.md
fix(doc): fix doc registerApp sandbox parameter.
> fix(doc): fix doc registerApp paramters

- packages/hooks/package.json
- pnpm-lock.yaml
The hook package does not declare a utils dependency
* The hook package does not declare a utils dependency
* Prompt exception：Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
* No need to add tests
> fix(hooks): The hook package does not declare a utils dependency

- website/docs/runtime/sandbox.md
> docs: add sandbox docs

- website/docs/guide/quickStart/quickStart.md
> docs: add stackblitz demo

- .github/workflows/documentation.yml
> ci(documentation): update time

- website/docs/api/registerApp.md
- website/docs/api/run.md
- website/docs/issues/childApp.md
- website/src/components/config/_basename.mdx
- website/src/components/config/_domGetter.mdx
- website/src/components/config/_sandbox.mdx
> docs: fix api error

- jest.config.js
- package.json
- pnpm-lock.yaml
use @swc/jest improve unit test performance
* make jest testing faster
> before
> after
* don't need add test
> workflow: use @swc/jest replace babel-jest and ts-jest

- packages/core/src/config.ts
fix(app): not filter insulationVariable config
> fix(app): not filter insulationVariable config

- website/docs/api/run.md
- website/docs/guide/demo/vite.md
- website/src/components/config/_insulationVariable.mdx
- website/src/components/config/_protectVariable.mdx
docs: add insulationvariable config docs
> docs: add insulationvariable config docs

- .github/workflows/ci.yml
- .gitignore
- .npmrc
- dev/app-angular/package.json
- dev/app-main/package.json
- dev/app-react-16/package.json
- dev/app-react-17/package.json
- dev/app-react-18/package.json
- dev/app-vue-2/package.json
- dev/app-vue-3/package.json
- dev/app-vue-vite/package.json
- dev/app-vue/package.json
- package.json
- packages/bridge/package.json
- packages/browser-snapshot/package.json
- packages/browser-vm/package.json
- packages/core/package.json
- packages/es-module/package.json
- packages/garfish/package.json
- packages/garfish/tsup.config.ts
- packages/hooks/package.json
- packages/loader/package.json
- packages/remote-module/package.json
- packages/router/package.json
- packages/utils/package.json
- pnpm-lock.yaml
- scripts/runE2eProject.js
- tsconfig.json
- tsup.config.ts
* use wireit to cache build file
* make the e2e faster
> workflow: use wireit to cache build file

- .pnpmfile.cjs
- package.json
- pnpm-lock.yaml
- website/docs/guide/demo/angular.md
- website/docs/guide/demo/demo.md
- website/docs/guide/demo/react.md
- website/docs/guide/demo/vite.md
- website/docs/guide/demo/vue.md
- website/docusaurus.config.js
- website/package.json
- website/src/pages/index.jsx
fix docs build fail after merge into main branch
> fix(docs): fix docs build fail

- packages/loader/package.json
- packages/loader/src/index.ts
- pnpm-lock.yaml
* fix(loader): remove fetch polyfill
> fix(loader): remove fetch polyfill

- packages/browser-vm/src/dynamicNode/processor.ts
fix(vm-sandbox): safe to define iframe global
> fix(vm-sandbox): safe to define iframe global

- package.json
- pnpm-lock.yaml
fix dependencies problem when run build
https://github.com/modern-js-dev/garfish/issues/515
I just wanna learn it.
Yep, when i modify it, every thing is correct
Yes and btw, CONTRIBUTING.md write node version is `>= 16.10` but package.json wanna `>=16.14.0`
> chore: fix dependencies when run build

- packages/browser-vm/src/dynamicNode/index.ts
* sub app element add element timing attribute
* can calculate app performance
> feat: elements timings

- website/docs/issues/childApp.md
> fix: remove repeat issues

- packages/loader/src/index.ts
> feat(loader): add `scope` parameter

- website/docs/api/channel.md
getXX 一般为函数
ps: 如果此处有其他考虑可以忽略此 pr
> Docs: Update channel.md

- cypress/e2e/1-the-whole-process/visit-sub-app.spec.js
- dev/app-main/src/config.ts
- dev/app-react-17/src/components/lazyComponent.tsx
- dev/app-react-17/src/index.tsx
- dev/util.js
- packages/browser-vm/src/dynamicNode/processor.ts
- packages/browser-vm/src/sandbox.ts
- packages/core/src/interface.ts
- packages/core/src/module/app.ts
- packages/utils/src/utils.ts
* fix sub-app document.currentscript property missing
* Clear document.currentScript setting in macro task
* document.currentScript for outputting sub-app synchronous and asynchronous scripts
> fix: currentscript attributes lost the property

- website/docs/api/run.md
sandbox api部分有内容重复 https://www.garfishjs.org/api/run#sandbox
> docs: update run.md

- packages/core/__tests__/__snapshots__/loadApp.spec.ts.snap
- packages/core/__tests__/esmLoader.spec.ts
- packages/core/__tests__/resources/scripts/no-entry.js
- packages/core/__tests__/resources/vueApp.html
- packages/core/src/interface.ts
- packages/core/src/module/app.ts
- packages/core/src/module/esModule.ts
- packages/utils/src/mimeType.ts
- website/docs/issues/childApp.md
To solve https://github.com/modern-js-dev/garfish/issues/545
> feat: support 'no-entry' json config

- website/docs/api/registerApp.md
sandbox api部分 registerApp 有内容重复 https://www.garfishjs.org/api/registerApp#sandbox
> docs: update registerApp.md

- website/docs/guide/demo/react.md
> docs: fix syntax error

- cypress/e2e/1-the-whole-process/visit-sub-app.spec.js
- cypress/e2e/2-the-vm-sandbox/set-global-variable.spec.js
- dev/app-main/src/config.ts
- dev/app-react-16/package.json
- dev/app-react-16/src/sandbox.tsx
- packages/browser-vm/__tests__/dom.spec.ts
- packages/browser-vm/src/dynamicNode/index.ts
- packages/browser-vm/src/dynamicNode/processor.ts
- packages/browser-vm/src/modules/document.ts
- packages/browser-vm/src/modules/network.ts
- packages/browser-vm/src/sandbox.ts
- pnpm-lock.yaml
* document instanceof Document === false
* prefix repair faiure
* sourceList include repeat data
> fix(sandbox): document instanceof Document、 pre fix、sourceList memory leak

- dev/app-main/src/garfishInit.ts
- website/docs/api/router.md
- API 增加 `routerChange` 的使用说明
- 针对 hook 全局唯一补充相应的使用提醒
None
None
None
> docs: update router hooks

- packages/browser-vm/__tests__/dynamic-link.spec.ts
- packages/browser-vm/__tests__/lock-queue.spec.ts
- packages/browser-vm/__tests__/resources/links/link-order-1.css
- packages/browser-vm/__tests__/resources/links/link-order-2.css
- packages/browser-vm/__tests__/resources/links/link-order-3.css
- packages/browser-vm/src/dynamicNode/processor.ts
- packages/browser-vm/src/utils.ts
- packages/core/__tests__/preloadApi.spec.ts
- packages/core/src/module/resource.ts
- packages/test-suite/src/mock.ts
- packages/utils/src/utils.ts
fix: link style render by order
> fix: link style render by order

- packages/router/__tests__/guard.spec.ts
- packages/router/src/agentRouter.ts
- packages/router/src/config.ts
- packages/router/src/linkTo.ts
* Not passing query correctly
* adding href
> fix: Not passing query correctly and adding href

- packages/browser-vm/src/dynamicNode/processor.ts
* fix(vm-sandbox): handling the style as a null value causes the style component style to fail to render normally
handling the style as a null value causes the style component style to fail to render normally
> fix(vm-sandbox): handling the style null value

- dev/app-main/src/config.ts
- packages/core/src/lifecycle.ts
- packages/core/src/module/app.ts
- packages/hooks/src/asyncWaterfallHooks.ts
- packages/hooks/src/syncWaterfallHook.ts
- packages/loader/src/managers/template.ts
- packages/utils/src/sentry.ts
1. add `customRender` hook
2. fix iframe src
> feat(core): custom node render

- packages/browser-vm/__tests__/fetch.spec.ts
- packages/browser-vm/src/modules/network.ts
- packages/browser-vm/src/types.ts
- packages/core/__tests__/sourceList.spec.ts
- packages/core/src/module/app.ts
- packages/utils/src/utils.ts
fix addSourceList can not support URL object type fetch request.
for more detail info please check the issue [#588 ](https://github.com/modern-js-dev/garfish/issues/588)
https://github.com/modern-js-dev/garfish/issues/588
> fix(core): fix addSourceList can not support URL object type fetch request

- packages/loader/src/index.ts
- packages/utils/src/utils.ts
> fix: cache resources are returned by macro tasks

- packages/loader/src/index.ts
- packages/utils/src/utils.ts
> 修复 loader 命中缓存资源的情况下，资源时序的问题

- packages/browser-vm/src/dynamicNode/processor.ts
- packages/browser-vm/src/sandbox.ts
- packages/core/src/interface.ts
- packages/core/src/module/app.ts
- packages/core/src/module/resource.ts
- packages/loader/src/managers/javascript.ts
- packages/utils/src/utils.ts
> 支持 defer 类型的脚本执行

- packages/utils/src/container.ts
domGetter为string且dom树下没有对应的节点，会导致无限递归
https://github.com/modern-js-dev/garfish/issues/607
> fix(core): domGetter为string且dom树下没有对应的节点，会导致无限递归(#607)

- packages/browser-vm/src/dynamicNode/index.ts
- packages/browser-vm/src/dynamicNode/processor.ts
- packages/core/src/module/app.ts
- packages/core/src/module/resource.ts
- packages/loader/src/index.ts
- packages/remote-module/src/actuator.ts
- packages/remote-module/src/apis/loadModuleSync.ts
- packages/remote-module/src/common.ts
> fix: 全部从 loader 上获取  managers，避免业务打包失误有多份构造函数

- packages/loader/src/index.ts
https://github.com/web-infra-dev/garfish/pull/605
> 修复 loader 命中 loadingList 资源的情况下，资源时序的问题

- README.ch.md
- README.md
- packages/bridge-react-v18/README.md
- packages/bridge-react/README.md
- packages/bridge-vue-v2/README.md
- packages/bridge-vue-v3/README.md
add credit announcement for bridge packages.
> chore: add credit announcement for bridge packages

- dev/app-main/src/config.ts
- packages/browser-vm/src/dynamicNode/index.ts
- packages/browser-vm/src/pluginify.ts
- packages/browser-vm/src/types.ts
- packages/core/src/config.ts
- packages/core/src/interface.ts
- website/src/components/config/_sandbox.mdx
fix: props deep merge
feat: add disableElementtiming config
> fix: props deep merge and add disableElementtiming config

- cypress/e2e/2-the-vm-sandbox/set-global-variable.spec.js
- dev/app-main/src/constant.ts
- dev/app-react-17/public/index.html
- dev/app-react-17/src/index.tsx
- packages/browser-vm/src/dynamicNode/processor.ts
- packages/browser-vm/src/pluginify.ts
- packages/browser-vm/src/sandbox.ts
- packages/browser-vm/src/types.ts
- packages/core/src/config.ts
- packages/core/src/interface.ts
- packages/core/src/module/app.ts
- website/src/components/config/_sandbox.mdx
* feat: add fixStaticResourceBaseUrl config
> feat: add fixStaticResourceBaseUrl config

- jest.config.js
- packages/browser-vm/__tests__/lock-queue.spec.ts
- packages/browser-vm/src/dynamicNode/processor.ts
- packages/browser-vm/src/utils.ts
* fix: vm-sandbox Render the link tag contents sequentially
> fix: vm-sandbox Render the link tag contents sequentially

- packages/utils/src/utils.ts
* fix: currentScript lose src attribute
> fix: currentScript lose src attribute

- packages/browser-vm/src/dynamicNode/processor.ts
* fix(sandbox): sandbox exec script error
> fix(sandbox): sandbox exec script error

- packages/core/src/config.ts
* feat: add global insulation variable
> feat: add global insulation variable

- website/docs/api/loadApp.md
> docs: update loadApp.md

- packages/browser-vm/src/dynamicNode/processor.ts
- packages/utils/src/utils.ts
* fix(sandbox): fix blob file transform url
> fix(sandbox): fix blob file transform url

- pnpm-lock.yaml
- pnpm-workspace.yaml
- website-new/docs/api/_meta.json
- website-new/docs/api/index.md
- website-new/docs/guide/concept/_meta.json
> fix(website): missing api getGlobal

- website-new/docs/guide/demo/react.mdx
> docs: fix invalid link

- website-new/docs/guide/quick-start/start.mdx
> fix(docs): fix link to Garfish API

- website-new/docs/guide/demo/react.mdx
> fix(docs): fix link to FAQ

- website-new/docs/guide/concept/bridge.mdx
- website-new/docs/guide/demo/angular.mdx
- website-new/docs/guide/demo/vite.mdx
- website-new/docs/guide/demo/vue.mdx
> Fix broken links

- website-new/docs/guide/quick-start/start.mdx
> fix(docs): typo start.mdx

- packages/browser-vm/src/dynamicNode/index.ts
fix(sandbo): fix appendChild arguments
> fix(sandbo): fix appendChild arguments

- README.ch.md
fix Documentaion title of About Garfish and Quick Start url link
[Problem link](https://github.com/web-infra-dev/garfish/blob/main/README.ch.md#%E6%96%87%E6%A1%A3)
[Erorr link](https://www.garfishjs.org/guide)
Issue: open About Garfish link jump to
[Erorr link](https://www.garfishjs.org/guide/start)
Issue: open Quick Start link jump to
My change after:
Open About Garfish link jump to
Open Quick Start link jump to
> docs: fix url link in README.ch.md
